#!/bin/bash

html-minifier --collapse-whitespace --remove-comments --remove-optional-tags --rem
ove-redundant-attributes --remove-script-type-attributes --remove-tag-whitespace --use-short-doctype --
minify-css true --minify-js true src/index.html > dist/index.html